In [42]:
# Exemple d'utilisation
country_code = 'FR'  # Code ISO pour la France
indicator_code = 'SP.POP.TOTL'


url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
url

'http://api.worldbank.org/v2/country/FR/indicator/SP.POP.TOTL'

In [43]:
import requests

country_code = 'FR'  # Code ISO pour la France
indicator_code = 'SP.POP.TOTL'
url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"

start_year = 2020
end_year = 2023

params = {
        'date': f'{start_year}:{end_year}',
        'format': 'json'
}

response = requests.get(url, params=params)
response

In [44]:
response.content

b'[{"page":1,"pages":1,"per_page":50,"total":4,"sourceid":"2","lastupdated":"2024-09-19"},[{"indicator":{"id":"SP.POP.TOTL","value":"Population, total"},"country":{"id":"FR","value":"France"},"countryiso3code":"FRA","date":"2023","value":68170228,"unit":"","obs_status":"","decimal":0},{"indicator":{"id":"SP.POP.TOTL","value":"Population, total"},"country":{"id":"FR","value":"France"},"countryiso3code":"FRA","date":"2022","value":67971311,"unit":"","obs_status":"","decimal":0},{"indicator":{"id":"SP.POP.TOTL","value":"Population, total"},"country":{"id":"FR","value":"France"},"countryiso3code":"FRA","date":"2021","value":67764304,"unit":"","obs_status":"","decimal":0},{"indicator":{"id":"SP.POP.TOTL","value":"Population, total"},"country":{"id":"FR","value":"France"},"countryiso3code":"FRA","date":"2020","value":67571107,"unit":"","obs_status":"","decimal":0}]]'

In [46]:
res = response.json()
res

[{'page': 1,
  'pages': 1,
  'per_page': 50,
  'total': 4,
  'sourceid': '2',
  'lastupdated': '2024-09-19'},
 [{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2023',
   'value': 68170228,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2022',
   'value': 67971311,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2021',
   'value': 67764304,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2020',
   'value': 67571107,
   'unit': '',
   'obs_status': '',
   'decimal': 0}]]

In [48]:
len(res)

2

In [47]:
res[0]

{'page': 1,
 'pages': 1,
 'per_page': 50,
 'total': 4,
 'sourceid': '2',
 'lastupdated': '2024-09-19'}

In [49]:
res[1]

[{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2023',
  'value': 68170228,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2022',
  'value': 67971311,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2021',
  'value': 67764304,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2020',
  'value': 67571107,
  'unit': '',
  'obs_status': '',
  'decimal': 0}]

In [2]:
import requests

def get_country_indicator_data(country_code, indicator_code, start_year, end_year):
    """
    Récupère les données d'indicateur d'un pays donné sur une plage de dates.
    
    :param country_code: Code ISO du pays (ex: 'FR' pour la France)
    :param indicator_code: Code de l'indicateur (ex: 'SP.POP.TOTL' pour la population totale)
    :param start_year: Année de début (ex: 2000)
    :param end_year: Année de fin (ex: 2023)
    :return: Données des indicateurs sous forme JSON
    """
    url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
    params = {
        'date': f'{start_year}:{end_year}',
        'format': 'json'
    }
    
    response = requests.get(url, params=params)
    
    if response.status_code == 200:
        data = response.json()
        # Les résultats sont dans la deuxième partie de la réponse JSON
        if len(data) > 1:
            return data[1]
        else:
            return None
    else:
        print(f"Erreur lors de la requête: {response.status_code}")
        return None

# Exemple d'utilisation
country_code = 'FR'  # Code ISO pour la France
indicator_code = 'SP.POP.TOTL'  # Population totale
start_year = 2000
end_year = 2023

data = get_country_indicator_data(country_code, indicator_code, start_year, end_year)

In [3]:
data

[{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2023',
  'value': 68170228,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2022',
  'value': 67971311,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2021',
  'value': 67764304,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2020',
  'value': 67571107,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2019',
  'value': 67388001,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2018',
  'value': 67158348,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2017',
  'value': 66918020,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2016',
  'value': 66724104,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2015',
  'value': 66548272,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2014',
  'value': 66312067,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2013',
  'value': 66002289,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2012',
  'value': 65662240,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2011',
  'value': 65345233,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2010',
  'value': 65030575,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2009',
  'value': 64710879,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2008',
  'value': 64379696,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2007',
  'value': 64021737,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2006',
  'value': 63628261,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2005',
  'value': 63188395,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2004',
  'value': 62716306,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2003',
  'value': 62256970,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2002',
  'value': 61816234,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2001',
  'value': 61367388,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2000',
  'value': 60921384,
  'unit': '',
  'obs_status': '',
  'decimal': 0}]

In [ ]:
if data:
    for entry in data:
        print(f"Année: {entry['date']}, Valeur: {entry['value']}")
else:
    print("Aucune donnée trouvée.")

In [4]:
indicators = {
    "PIB par habitant": 'NY.GDP.PCAP.CD',
    "PNB": 'NY.GNP.MKTP.CD',
    "PNB par habitant": 'NY.GNP.PCAP.CD',
    "Exportations": 'NE.EXP.GNFS.CD',
    "Importations": 'NE.IMP.GNFS.CD',
    "Dette externe": 'DT.DOD.DECT.CD',
    "Taux de croissance du PIB": 'NY.GDP.MKTP.KD.ZG',
    "Population totale": 'SP.POP.TOTL',
    "Taux de croissance de la population": 'SP.POP.GROW',
    "Indice de fécondité": 'SP.DYN.TFRT.IN',
    "Gini": 'SI.POV.GINI',
    "Inflation (Indice des prix à la consommation)": 'FP.CPI.TOTL.ZG',
    "Taux d'intérêt réel": 'FR.INR.RINR',
    "Taux d'intérêt sur les prêts": 'FR.INR.LEND',
    "Taux d'intérêt sur les dépôts": 'FR.INR.DPST',
    "Dette publique totale (% du PIB)": 'GC.DOD.TOTL.GD.ZS',
    "Dette publique totale (USD)": 'GC.DOD.TOTL.CN',
    "Taux de chômage": 'SL.UEM.TOTL.ZS'
}

country_code = 'FR'  # France
start_year = 2000
end_year = 2023

for name, indicator_code in indicators.items():
    print(f"\n{name} ({indicator_code}) :")
    data = get_country_indicator_data(country_code, indicator_code, start_year, end_year)
    
    if data:
        for entry in data:
            print(f"Année: {entry['date']}, Valeur: {entry['value']}")
    else:
        print("Aucune donnée trouvée.")

PIB par habitant (NY.GDP.PCAP.CD) :
Année: 2023, Valeur: 44460.8178457009
Année: 2022, Valeur: 40886.2532680273
Année: 2021, Valeur: 43671.3084099631
Année: 2020, Valeur: 39179.7442596057
Année: 2019, Valeur: 40494.8982936276
Année: 2018, Valeur: 41557.8548588876
Année: 2017, Valeur: 38781.0494870836
Année: 2016, Valeur: 37062.5335723829
Année: 2015, Valeur: 36652.9223052178
Année: 2014, Valeur: 43068.5487241739
Année: 2013, Valeur: 42602.7179652667
Année: 2012, Valeur: 40870.8523645734
Année: 2011, Valeur: 43846.4660764798
Année: 2010, Valeur: 40676.0647913181
Année: 2009, Valeur: 41737.7635518137
Année: 2008, Valeur: 45515.9617533473
Année: 2007, Valeur: 41557.6235648179
Année: 2006, Valeur: 36470.2128399313
Année: 2005, Valeur: 34768.1759037525
Année: 2004, Valeur: 33797.1624418436
Année: 2003, Valeur: 29627.92426353
Année: 2002, Valeur: 24288.2700193508
Année: 2001, Valeur: 22449.3396931175
Année: 2000, Valeur: 22416.425417915

PNB (NY.GNP.MKTP.CD) :
Année: 2023, Valeur: 3078891305966.05
Année: 2022, Valeur: 2828314888998.07
Année: 2021, Valeur: 3024516531073.59
Année: 2020, Valeur: 2667982790343.98
Année: 2019, Valeur: 2787416524619.6
Année: 2018, Valeur: 2855661376338.82
Année: 2017, Valeur: 2653805221561.18
Année: 2016, Valeur: 2525276585700.01
Année: 2015, Valeur: 2491864986670.7
Année: 2014, Valeur: 2917864654134.5
Année: 2013, Valeur: 2874861573220.79
Année: 2012, Valeur: 2742349300400.39
Année: 2011, Valeur: 2941328117344.36
Année: 2010, Valeur: 2706418757800.01
Année: 2009, Valeur: 2763004002090.23
Année: 2008, Valeur: 2994136038927.34
Année: 2007, Valeur: 2713440990838.05
Année: 2006, Valeur: 2366964499002.35
Année: 2005, Valeur: 2234564034091.83
Année: 2004, Valeur: 2148978081185.33
Année: 2003, Valeur: 1869026496404.31
Année: 2002, Valeur: 1517047281243.53
Année: 2001, Valeur: 1402495832979.14
Année: 2000, Valeur: 1387213402712.16

PNB par habitant (NY.GNP.PCAP.CD) :
Année: 2023, Valeur: 45070
Année: 2022, Valeur: 45290
Année: 2021, Valeur: 43810
Année: 2020, Valeur: 39250
Année: 2019, Valeur: 42460
Année: 2018, Valeur: 41170
Année: 2017, Valeur: 38320
Année: 2016, Valeur: 39100
Année: 2015, Valeur: 41130
Année: 2014, Valeur: 43340
Année: 2013, Valeur: 43800
Année: 2012, Valeur: 43410
Année: 2011, Valeur: 44440
Année: 2010, Valeur: 43970
Année: 2009, Valeur: 44070
Année: 2008, Valeur: 43540
Année: 2007, Valeur: 40160
Année: 2006, Valeur: 37880
Année: 2005, Valeur: 35920
Année: 2004, Valeur: 31450
Année: 2003, Valeur: 26000
Année: 2002, Valeur: 23150
Année: 2001, Valeur: 23870
Année: 2000, Valeur: 24990

Exportations (NE.EXP.GNFS.CD) :
Année: 2023, Valeur: 990482069684.331
Année: 2022, Valeur: 963967041638.136
Année: 2021, Valeur: 888842353166.652
Année: 2020, Valeur: 723479579565.761
Année: 2019, Valeur: 862106200525.489
Année: 2018, Valeur: 885114776507.45
Année: 2017, Valeur: 803163777629.413
Année: 2016, Valeur: 748010809661.091
Année: 2015, Valeur: 746211770692.968
Année: 2014, Valeur: 847269974207.056
Année: 2013, Valeur: 825700281806.669
Année: 2012, Valeur: 783713381111.719
Année: 2011, Valeur: 814316094241.247
Année: 2010, Valeur: 708600861200.001
Année: 2009, Valeur: 670780157110.546
Année: 2008, Valeur: 823983397589.844
Année: 2007, Valeur: 741061331101.179
Année: 2006, Valeur: 648243071809.411
Année: 2005, Valeur: 593901326045.136
Année: 2004, Valeur: 561042237466.411
Année: 2003, Valeur: 481646963819.999
Année: 2002, Valeur: 413353771803.138
Année: 2001, Valeur: 389407179769.292
Année: 2000, Valeur: 390504309338.04

Importations (NE.IMP.GNFS.CD) :
Année: 2023, Valeur: 1057715352939.23
Année: 2022, Valeur: 1071713925243.19
Année: 2021, Valeur: 944547056290.682
Année: 2020, Valeur: 779781852364.204
Année: 2019, Valeur: 888231377160.783
Année: 2018, Valeur: 913320694019.607
Année: 2017, Valeur: 830791260481.178
Année: 2016, Valeur: 762973925940.469
Année: 2015, Valeur: 760028534719.922
Année: 2014, Valeur: 879982977519.997
Année: 2013, Valeur: 854791379337.649
Année: 2012, Valeur: 818493895248.047
Année: 2011, Valeur: 870126540107.006
Année: 2010, Valeur: 742755299683.335
Année: 2009, Valeur: 692153802943.359
Année: 2008, Valeur: 857925492297.656
Année: 2007, Valeur: 760064379592.944
Année: 2006, Valeur: 653657213936.47
Année: 2005, Valeur: 592025237914.397
Année: 2004, Valeur: 539577459091.121
Année: 2003, Valeur: 455341828900.391
Année: 2002, Valeur: 383474587651.373
Année: 2001, Valeur: 367744588386.221
Année: 2000, Valeur: 372359017200.001

Dette externe (DT.DOD.DECT.CD) :
Année: 2023, Valeur: None
Année: 2022, Valeur: None
Année: 2021, Valeur: None
Année: 2020, Valeur: None
Année: 2019, Valeur: None
Année: 2018, Valeur: None
Année: 2017, Valeur: None
Année: 2016, Valeur: None
Année: 2015, Valeur: None
Année: 2014, Valeur: None
Année: 2013, Valeur: None
Année: 2012, Valeur: None
Année: 2011, Valeur: None
Année: 2010, Valeur: None
Année: 2009, Valeur: None
Année: 2008, Valeur: None
Année: 2007, Valeur: None
Année: 2006, Valeur: None
Année: 2005, Valeur: None
Année: 2004, Valeur: None
Année: 2003, Valeur: None
Année: 2002, Valeur: None
Année: 2001, Valeur: None
Année: 2000, Valeur: None

Taux de croissance du PIB (NY.GDP.MKTP.KD.ZG) :
Année: 2023, Valeur: 0.703718546620237
Année: 2022, Valeur: 2.45475817660707
Année: 2021, Valeur: 6.43520962104938
Année: 2020, Valeur: -7.54045916249407
Année: 2019, Valeur: 1.84297181445896
Année: 2018, Valeur: 1.86506607081999
Année: 2017, Valeur: 2.29141999417021
Année: 2016, Valeur: 1.09546440372048
Année: 2015, Valeur: 1.1129123405747
Année: 2014, Valeur: 0.956183052371557
Année: 2013, Valeur: 0.576326674771792
Année: 2012, Valeur: 0.313134751077172
Année: 2011, Valeur: 2.19270063266654
Année: 2010, Valeur: 1.94943762312663
Année: 2009, Valeur: -2.87331382849632
Année: 2008, Valeur: 0.254945960124033
Année: 2007, Valeur: 2.42473624337305
Année: 2006, Valeur: 2.44932360111885
Année: 2005, Valeur: 1.66321998030079
Année: 2004, Valeur: 2.82975292869891
Année: 2003, Valeur: 0.823160756684118
Année: 2002, Valeur: 1.13553148214601
Année: 2001, Valeur: 1.98372141863292
Année: 2000, Valeur: 3.92366922704063

Population totale (SP.POP.TOTL) :
Année: 2023, Valeur: 68170228
Année: 2022, Valeur: 67971311
Année: 2021, Valeur: 67764304
Année: 2020, Valeur: 67571107
Année: 2019, Valeur: 67388001
Année: 2018, Valeur: 67158348
Année: 2017, Valeur: 66918020
Année: 2016, Valeur: 66724104
Année: 2015, Valeur: 66548272
Année: 2014, Valeur: 66312067
Année: 2013, Valeur: 66002289
Année: 2012, Valeur: 65662240
Année: 2011, Valeur: 65345233
Année: 2010, Valeur: 65030575
Année: 2009, Valeur: 64710879
Année: 2008, Valeur: 64379696
Année: 2007, Valeur: 64021737
Année: 2006, Valeur: 63628261
Année: 2005, Valeur: 63188395
Année: 2004, Valeur: 62716306
Année: 2003, Valeur: 62256970
Année: 2002, Valeur: 61816234
Année: 2001, Valeur: 61367388
Année: 2000, Valeur: 60921384

Taux de croissance de la population (SP.POP.GROW) :
Année: 2023, Valeur: 0.292221085514903
Année: 2022, Valeur: 0.305015246719983
Année: 2021, Valeur: 0.285508618638434
Année: 2020, Valeur: 0.271350507669993
Année: 2019, Valeur: 0.341374143157509
Année: 2018, Valeur: 0.358494581816163
Année: 2017, Valeur: 0.29020211635109
Année: 2016, Valeur: 0.263868788565368
Année: 2015, Valeur: 0.355569240058298
Année: 2014, Valeur: 0.46824634207038
Année: 2013, Valeur: 0.516539661307546
Année: 2012, Valeur: 0.483953489768883
Année: 2011, Valeur: 0.482694781758347
Année: 2010, Valeur: 0.492821125690305
Année: 2009, Valeur: 0.513102876178491
Année: 2008, Valeur: 0.557563757631959
Année: 2007, Valeur: 0.616493932446319
Année: 2006, Valeur: 0.693706612114177
Année: 2005, Valeur: 0.749918325024531
Année: 2004, Valeur: 0.735098067563242
Année: 2003, Valeur: 0.710448089652969
Année: 2002, Valeur: 0.728746206873967
Année: 2001, Valeur: 0.729430789508821
Année: 2000, Valeur: 0.686782586857032

Indice de fécondité (SP.DYN.TFRT.IN) :
Année: 2023, Valeur: None
Année: 2022, Valeur: 1.794
Année: 2021, Valeur: 1.84
Année: 2020, Valeur: 1.83
Année: 2019, Valeur: 1.86
Année: 2018, Valeur: 1.87
Année: 2017, Valeur: 1.89
Année: 2016, Valeur: 1.92
Année: 2015, Valeur: 1.96
Année: 2014, Valeur: 2
Année: 2013, Valeur: 1.99
Année: 2012, Valeur: 2.01
Année: 2011, Valeur: 2.01
Année: 2010, Valeur: 2.03
Année: 2009, Valeur: 2
Année: 2008, Valeur: 2.01
Année: 2007, Valeur: 1.98
Année: 2006, Valeur: 2
Année: 2005, Valeur: 1.94
Année: 2004, Valeur: 1.92
Année: 2003, Valeur: 1.89
Année: 2002, Valeur: 1.88
Année: 2001, Valeur: 1.9
Année: 2000, Valeur: 1.89

Gini (SI.POV.GINI) :
Année: 2023, Valeur: None
Année: 2022, Valeur: None
Année: 2021, Valeur: 31.5
Année: 2020, Valeur: 30.7
Année: 2019, Valeur: 31.2
Année: 2018, Valeur: 32.4
Année: 2017, Valeur: 31.6
Année: 2016, Valeur: 31.9
Année: 2015, Valeur: 32.7
Année: 2014, Valeur: 32.3
Année: 2013, Valeur: 32.5
Année: 2012, Valeur: 33.1
Année: 2011, Valeur: 33.3
Année: 2010, Valeur: 33.7
Année: 2009, Valeur: 32.7
Année: 2008, Valeur: 33
Année: 2007, Valeur: 32.4
Année: 2006, Valeur: 29.7
Année: 2005, Valeur: 29.8
Année: 2004, Valeur: 30.6
Année: 2003, Valeur: 31.4
Année: 2002, Valeur: 31.8
Année: 2001, Valeur: 32.5
Année: 2000, Valeur: 32.6

Inflation (Indice des prix à la consommation) (FP.CPI.TOTL.ZG) :
Année: 2023, Valeur: 4.87835726508441
Année: 2022, Valeur: 5.22236748369735
Année: 2021, Valeur: 1.64233141038385
Année: 2020, Valeur: 0.476498852725066
Année: 2019, Valeur: 1.10825492288294
Année: 2018, Valeur: 1.85081508315502
Année: 2017, Valeur: 1.03228275064662
Année: 2016, Valeur: 0.18333486112386
Année: 2015, Valeur: 0.0375143805125182
Année: 2014, Valeur: 0.50775882293799
Année: 2013, Valeur: 0.863715497861805
Année: 2012, Valeur: 1.9541953161351
Année: 2011, Valeur: 2.11159795174994
Année: 2010, Valeur: 1.53112270420926
Année: 2009, Valeur: 0.0876204781574552
Année: 2008, Valeur: 2.81286194914787
Année: 2007, Valeur: 1.4879980595386
Année: 2006, Valeur: 1.67512449608723
Année: 2005, Valeur: 1.74586936380482
Année: 2004, Valeur: 2.14208964640241
Année: 2003, Valeur: 2.09847219146923
Année: 2002, Valeur: 1.9234122872706
Année: 2001, Valeur: 1.63478079549601
Année: 2000, Valeur: 1.67595988720927

Taux d'intérêt réel (FR.INR.RINR) :
Année: 2023, Valeur: None
Année: 2022, Valeur: None
Année: 2021, Valeur: None
Année: 2020, Valeur: None
Année: 2019, Valeur: None
Année: 2018, Valeur: None
Année: 2017, Valeur: None
Année: 2016, Valeur: None
Année: 2015, Valeur: None
Année: 2014, Valeur: None
Année: 2013, Valeur: None
Année: 2012, Valeur: None
Année: 2011, Valeur: None
Année: 2010, Valeur: None
Année: 2009, Valeur: None
Année: 2008, Valeur: None
Année: 2007, Valeur: None
Année: 2006, Valeur: None
Année: 2005, Valeur: None
Année: 2004, Valeur: None
Année: 2003, Valeur: None
Année: 2002, Valeur: None
Année: 2001, Valeur: None
Année: 2000, Valeur: None

Taux d'intérêt sur les prêts (FR.INR.LEND) :
Année: 2023, Valeur: None
Année: 2022, Valeur: None
Année: 2021, Valeur: None
Année: 2020, Valeur: None
Année: 2019, Valeur: None
Année: 2018, Valeur: None
Année: 2017, Valeur: None
Année: 2016, Valeur: None
Année: 2015, Valeur: None
Année: 2014, Valeur: None
Année: 2013, Valeur: None
Année: 2012, Valeur: None
Année: 2011, Valeur: None
Année: 2010, Valeur: None
Année: 2009, Valeur: None
Année: 2008, Valeur: None
Année: 2007, Valeur: None
Année: 2006, Valeur: None
Année: 2005, Valeur: None
Année: 2004, Valeur: None
Année: 2003, Valeur: None
Année: 2002, Valeur: None
Année: 2001, Valeur: None
Année: 2000, Valeur: None

Taux d'intérêt sur les dépôts (FR.INR.DPST) :
Année: 2023, Valeur: None
Année: 2022, Valeur: None
Année: 2021, Valeur: None
Année: 2020, Valeur: None
Année: 2019, Valeur: None
Année: 2018, Valeur: None
Année: 2017, Valeur: 0.791666666666667
Année: 2016, Valeur: 0.7575
Année: 2015, Valeur: 0.895833333333333
Année: 2014, Valeur: 1.14583333333333
Année: 2013, Valeur: 1.59666666666667
Année: 2012, Valeur: 2.25
Année: 2011, Valeur: 2.08333333333333
Année: 2010, Valeur: 1.45833333333333
Année: 2009, Valeur: 1.91666666666667
Année: 2008, Valeur: 3.66666666666667
Année: 2007, Valeur: 2.85416666666667
Année: 2006, Valeur: 2.4375
Année: 2005, Valeur: 2.14583333333333
Année: 2004, Valeur: 2.25
Année: 2003, Valeur: 2.6875
Année: 2002, Valeur: 3
Année: 2001, Valeur: 3
Année: 2000, Valeur: 2.625

Dette publique totale (% du PIB) (GC.DOD.TOTL.GD.ZS) :
Année: 2023, Valeur: None
Année: 2022, Valeur: 98.6605241499728
Année: 2021, Valeur: 116.886773525469
Année: 2020, Valeur: 123.172171235879
Année: 2019, Valeur: 104.961161125435
Année: 2018, Valeur: 101.622134416787
Année: 2017, Valeur: 102.21526508744
Année: 2016, Valeur: 102.262044850588
Année: 2015, Valeur: 97.9803332557022
Année: 2014, Valeur: 97.5543838512582
Année: 2013, Valeur: 90.9685436680429
Année: 2012, Valeur: 90.2797486025496
Année: 2011, Valeur: 82.2922420615546
Année: 2010, Valeur: 80.3012997114704
Année: 2009, Valeur: 77.9477820433769
Année: 2008, Valeur: 65.372569489756
Année: 2007, Valeur: 59.4874211892694
Année: 2006, Valeur: 60.9742926849592
Année: 2005, Valeur: 65.6111738740193
Année: 2004, Valeur: 64.6424130247374
Année: 2003, Valeur: 63.6735542410279
Année: 2002, Valeur: 61.1765498677754
Année: 2001, Valeur: 57.8188792094656
Année: 2000, Valeur: 58.2992523257033

Dette publique totale (USD) (GC.DOD.TOTL.CN) :
Année: 2023, Valeur: None
Année: 2022, Valeur: 2603742000000
Année: 2021, Valeur: 2924645000000
Année: 2020, Valeur: 2854924000000
Année: 2019, Valeur: 2558570000000
Année: 2018, Valeur: 2401642000000
Année: 2017, Valeur: 2348132000000
Année: 2016, Valeur: 2284666000000
Année: 2015, Valeur: 2154031000000
Année: 2014, Valeur: 2097190000000
Année: 2013, Valeur: 1925976000000
Année: 2012, Valeur: 1885767000000
Année: 2011, Valeur: 1693878000000
Année: 2010, Valeur: 1602243000000
Année: 2009, Valeur: 1509398000000
Année: 2008, Valeur: 1302470000000
Année: 2007, Valeur: 1154865000000
Année: 2006, Valeur: 1126897000000
Année: 2005, Valeur: 1158631000000
Année: 2004, Valeur: 1101519000000
Année: 2003, Valeur: 1038303000000
Année: 2002, Valeur: 971379000000
Année: 2001, Valeur: 889370000000
Année: 2000, Valeur: 862004000000

Taux de chômage (SL.UEM.TOTL.ZS) :
Année: 2023, Valeur: 7.323
Année: 2022, Valeur: 7.308
Année: 2021, Valeur: 7.874
Année: 2020, Valeur: 8.01
Année: 2019, Valeur: 8.415
Année: 2018, Valeur: 9.018
Année: 2017, Valeur: 9.41
Année: 2016, Valeur: 10.057
Année: 2015, Valeur: 10.354
Année: 2014, Valeur: 10.273
Année: 2013, Valeur: 9.913
Année: 2012, Valeur: 9.841
Année: 2011, Valeur: 9.228
Année: 2010, Valeur: 9.279
Année: 2009, Valeur: 9.122
Année: 2008, Valeur: 7.386
Année: 2007, Valeur: 8.009
Année: 2006, Valeur: 8.833
Année: 2005, Valeur: 8.882
Année: 2004, Valeur: 8.914
Année: 2003, Valeur: 8.307
Année: 2002, Valeur: 8.702
Année: 2001, Valeur: 8.61
Année: 2000, Valeur: 10.218

In [5]:
data

[{'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2023',
  'value': 7.323,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2022',
  'value': 7.308,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2021',
  'value': 7.874,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2020',
  'value': 8.01,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2019',
  'value': 8.415,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2018',
  'value': 9.018,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2017',
  'value': 9.41,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2016',
  'value': 10.057,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2015',
  'value': 10.354,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2014',
  'value': 10.273,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2013',
  'value': 9.913,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2012',
  'value': 9.841,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2011',
  'value': 9.228,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2010',
  'value': 9.279,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2009',
  'value': 9.122,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2008',
  'value': 7.386,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2007',
  'value': 8.009,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2006',
  'value': 8.833,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2005',
  'value': 8.882,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2004',
  'value': 8.914,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2003',
  'value': 8.307,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2002',
  'value': 8.702,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2001',
  'value': 8.61,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'SL.UEM.TOTL.ZS',
   'value': 'Unemployment, total (% of total labor force) (modeled ILO estimate)'},
  'country': {'id': 'FR', 'value': 'France'},
  'countryiso3code': 'FRA',
  'date': '2000',
  'value': 10.218,
  'unit': '',
  'obs_status': '',
  'decimal': 1}]

In [13]:
import requests
import pandas as pd

def get_country_indicator_data(country_code, indicator_code, start_year, end_year):
    url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
    params = {
        "date": f"{start_year}:{end_year}",
        "format": "json",
        "per_page": 1000
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data and len(data) > 1:
            return data[1]  # the data is in the second element of the response
    return None

# Liste pour stocker les résultats
all_data = []

indicators = {
    "PIB par habitant": 'NY.GDP.PCAP.CD',
    "PNB": 'NY.GNP.MKTP.CD',
    "PNB par habitant": 'NY.GNP.PCAP.CD',
    "Exportations": 'NE.EXP.GNFS.CD',
    "Importations": 'NE.IMP.GNFS.CD',
    "Dette externe": 'DT.DOD.DECT.CD',
    "Taux de croissance du PIB": 'NY.GDP.MKTP.KD.ZG',
    "Population totale": 'SP.POP.TOTL',
    "Taux de croissance de la population": 'SP.POP.GROW',
    "Indice de fécondité": 'SP.DYN.TFRT.IN',
    "Gini": 'SI.POV.GINI',
    "Inflation (Indice des prix à la consommation)": 'FP.CPI.TOTL.ZG',
    "Taux d'intérêt réel": 'FR.INR.RINR',
    "Taux d'intérêt sur les prêts": 'FR.INR.LEND',
    "Taux d'intérêt sur les dépôts": 'FR.INR.DPST',
    "Dette publique totale (% du PIB)": 'GC.DOD.TOTL.GD.ZS',
    "Dette publique totale (USD)": 'GC.DOD.TOTL.CN',
    "Taux de chômage": 'SL.UEM.TOTL.ZS'
}

country_code = 'FR'  # France
start_year = 2000
end_year = 2023

# Parcourir les indicateurs et récupérer les données
for name, indicator_code in indicators.items():
    data = get_country_indicator_data(country_code, indicator_code, start_year, end_year)
    if data:
        for entry in data:
            all_data.append({
                "Code indicateur": indicator_code,
                "Indicateur": name,
                "Année": entry['date'],
                "Valeur": entry['value']
            })

# Convertir la liste en DataFrame
df = pd.DataFrame(all_data)

# Affichage du DataFrame
df.head(2)

  Code indicateur        Indicateur Année        Valeur
0  NY.GDP.PCAP.CD  PIB par habitant  2023  44460.817846
1  NY.GDP.PCAP.CD  PIB par habitant  2022  40886.253268

In [14]:
df.shape

(432, 4)

In [18]:
df[df["Année"] == "2022" ]

,Code indicateur,Indicateur,Année,Valeur
1,NY.GDP.PCAP.CD,PIB par habitant,2022,4.088625e+04
25,NY.GNP.MKTP.CD,PNB,2022,2.828315e+12
49,NY.GNP.PCAP.CD,PNB par habitant,2022,4.529000e+04
73,NE.EXP.GNFS.CD,Exportations,2022,9.639670e+11
97,NE.IMP.GNFS.CD,Importations,2022,1.071714e+12
121,DT.DOD.DECT.CD,Dette externe,2022,NaN
145,NY.GDP.MKTP.KD.ZG,Taux de croissance du PIB,2022,2.454758e+00
169,SP.POP.TOTL,Population totale,2022,6.797131e+07
193,SP.POP.GROW,Taux de croissance de la population,2022,3.050152e-01
217,SP.DYN.TFRT.IN,Indice de fécondité,2022,1.794000e+00
241,SI.POV.GINI,Gini,2022,NaN
265,FP.CPI.TOTL.ZG,Inflation (Indice des prix à la consommation),2022,5.222367e+00
289,FR.INR.RINR,Taux d'intérêt réel,2022,NaN
313,FR.INR.LEND,Taux d'intérêt sur les prêts,2022,NaN
337,FR.INR.DPST,Taux d'intérêt sur les dépôts,2022,NaN
361,GC.DOD.TOTL.GD.ZS,Dette publique totale (% du PIB),2022,9.866052e+01
385,GC.DOD.TOTL.CN,Dette publique totale (USD),2022,2.603742e+12
409,SL.UEM.TOTL.ZS,Taux de chômage,2022,7.308000e+00

In [15]:
df.head(30)

   Code indicateur        Indicateur Année        Valeur
0   NY.GDP.PCAP.CD  PIB par habitant  2023  4.446082e+04
1   NY.GDP.PCAP.CD  PIB par habitant  2022  4.088625e+04
2   NY.GDP.PCAP.CD  PIB par habitant  2021  4.367131e+04
3   NY.GDP.PCAP.CD  PIB par habitant  2020  3.917974e+04
4   NY.GDP.PCAP.CD  PIB par habitant  2019  4.049490e+04
5   NY.GDP.PCAP.CD  PIB par habitant  2018  4.155785e+04
6   NY.GDP.PCAP.CD  PIB par habitant  2017  3.878105e+04
7   NY.GDP.PCAP.CD  PIB par habitant  2016  3.706253e+04
8   NY.GDP.PCAP.CD  PIB par habitant  2015  3.665292e+04
9   NY.GDP.PCAP.CD  PIB par habitant  2014  4.306855e+04
10  NY.GDP.PCAP.CD  PIB par habitant  2013  4.260272e+04
11  NY.GDP.PCAP.CD  PIB par habitant  2012  4.087085e+04
12  NY.GDP.PCAP.CD  PIB par habitant  2011  4.384647e+04
13  NY.GDP.PCAP.CD  PIB par habitant  2010  4.067606e+04
14  NY.GDP.PCAP.CD  PIB par habitant  2009  4.173776e+04
15  NY.GDP.PCAP.CD  PIB par habitant  2008  4.551596e+04
16  NY.GDP.PCAP.CD  PIB par habitant  2007  4.155762e+04
17  NY.GDP.PCAP.CD  PIB par habitant  2006  3.647021e+04
18  NY.GDP.PCAP.CD  PIB par habitant  2005  3.476818e+04
19  NY.GDP.PCAP.CD  PIB par habitant  2004  3.379716e+04
20  NY.GDP.PCAP.CD  PIB par habitant  2003  2.962792e+04
21  NY.GDP.PCAP.CD  PIB par habitant  2002  2.428827e+04
22  NY.GDP.PCAP.CD  PIB par habitant  2001  2.244934e+04
23  NY.GDP.PCAP.CD  PIB par habitant  2000  2.241643e+04
24  NY.GNP.MKTP.CD               PNB  2023  3.078891e+12
25  NY.GNP.MKTP.CD               PNB  2022  2.828315e+12
26  NY.GNP.MKTP.CD               PNB  2021  3.024517e+12
27  NY.GNP.MKTP.CD               PNB  2020  2.667983e+12
28  NY.GNP.MKTP.CD               PNB  2019  2.787417e+12
29  NY.GNP.MKTP.CD               PNB  2018  2.855661e+12

In [20]:
import requests
import pandas as pd

def get_country_indicator_data(country_code, indicator_code, start_year, end_year):
    url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
    params = {
        "date": f"{start_year}:{end_year}",
        "format": "json",
        "per_page": 1000
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data and len(data) > 1:
            return data[1]  # les données sont dans le deuxième élément de la réponse
    return None

# Liste des pays et leurs codes (exemple avec Etats-Unis, Chine, France, Angleterre, Allemagne, et Cameroun)
countries = {
    "Etats-Unis": "US",
    "Chine": "CN",
    "France": 'FR',
    "Royaume-Uni": "GB",
    "Allemagne": 'DE',
    "Cameroun": 'CM'
}

# Liste pour stocker les résultats
all_data = []

# Indicateurs à récupérer
indicators = {
    "PIB par habitant": 'NY.GDP.PCAP.CD',
    "PNB": 'NY.GNP.MKTP.CD',
    "PNB par habitant": 'NY.GNP.PCAP.CD',
    "Exportations": 'NE.EXP.GNFS.CD',
    "Importations": 'NE.IMP.GNFS.CD',
    "Dette externe": 'DT.DOD.DECT.CD',
    "Taux de croissance du PIB": 'NY.GDP.MKTP.KD.ZG',
    "Population totale": 'SP.POP.TOTL',
    "Taux de croissance de la population": 'SP.POP.GROW',
    "Indice de fécondité": 'SP.DYN.TFRT.IN',
    "Gini": 'SI.POV.GINI',
    "Inflation (Indice des prix à la consommation)": 'FP.CPI.TOTL.ZG',
    "Taux d'intérêt réel": 'FR.INR.RINR',
    "Taux de chômage": 'SL.UEM.TOTL.ZS'
}

start_year = 2000
end_year = 2023

# Parcourir les pays et les indicateurs pour récupérer les données
for country_name, country_code in countries.items():
    for name, indicator_code in indicators.items():
        data = get_country_indicator_data(country_code, indicator_code, start_year, end_year)
        if data:
            for entry in data:
                all_data.append({
                    "Pays": country_name,
                    "Code pays": country_code,
                    "Indicateur": name,
                    "Code indicateur": indicator_code,
                    "Année": entry['date'],
                    "Valeur": entry['value']
                })

# Convertir la liste en DataFrame
df_countries = pd.DataFrame(all_data)


# Affichage du DataFrame
print(df_countries.shape)

(2016, 6)

In [32]:
df_countries['Valeur'] = df_countries['Valeur'].apply(lambda x: "{:,.2f}".format(x) if pd.notnull(x) else x)

In [33]:
df_countries.head(10)

         Pays Code pays        Indicateur Code indicateur Année     Valeur
0  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2023  81,695.19
1  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2022  77,246.67
2  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2021  71,055.88
3  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2020  64,317.40
4  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2019  65,548.07
5  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2018  63,201.05
6  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2017  60,322.26
7  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2016  58,206.61
8  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2015  57,040.21
9  Etats-Unis        US  PIB par habitant  NY.GDP.PCAP.CD  2014  55,304.32

In [34]:
df_countries[df_countries["Année"] == "2022" ].head(14)

,Pays,Code pays,Indicateur,Code indicateur,Année,Valeur
1,Etats-Unis,US,PIB par habitant,NY.GDP.PCAP.CD,2022,"77,246.67"
25,Etats-Unis,US,PNB,NY.GNP.MKTP.CD,2022,"25,926,000,000,000.00"
49,Etats-Unis,US,PNB par habitant,NY.GNP.PCAP.CD,2022,"76,590.00"
73,Etats-Unis,US,Exportations,NE.EXP.GNFS.CD,2022,"2,995,046,000,000.00"
97,Etats-Unis,US,Importations,NE.IMP.GNFS.CD,2022,"3,966,165,000,000.00"
121,Etats-Unis,US,Dette externe,DT.DOD.DECT.CD,2022,NaN
145,Etats-Unis,US,Taux de croissance du PIB,NY.GDP.MKTP.KD.ZG,2022,1.94
169,Etats-Unis,US,Population totale,SP.POP.TOTL,2022,"333,271,411.00"
193,Etats-Unis,US,Taux de croissance de la population,SP.POP.GROW,2022,0.37
217,Etats-Unis,US,Indice de fécondité,SP.DYN.TFRT.IN,2022,1.67
241,Etats-Unis,US,Gini,SI.POV.GINI,2022,41.30
265,Etats-Unis,US,Inflation (Indice des prix à la consommation),FP.CPI.TOTL.ZG,2022,8.00
289,Etats-Unis,US,Taux d'intérêt réel,FR.INR.RINR,2022,NaN
313,Etats-Unis,US,Taux de chômage,SL.UEM.TOTL.ZS,2022,3.65

In [35]:
df_countries[(df_countries["Année"] == "2022") & (df_countries["Code pays"] == "FR") ]

,Pays,Code pays,Indicateur,Code indicateur,Année,Valeur
673,France,FR,PIB par habitant,NY.GDP.PCAP.CD,2022,"40,886.25"
697,France,FR,PNB,NY.GNP.MKTP.CD,2022,"2,828,314,888,998.07"
721,France,FR,PNB par habitant,NY.GNP.PCAP.CD,2022,"45,290.00"
745,France,FR,Exportations,NE.EXP.GNFS.CD,2022,"963,967,041,638.14"
769,France,FR,Importations,NE.IMP.GNFS.CD,2022,"1,071,713,925,243.19"
793,France,FR,Dette externe,DT.DOD.DECT.CD,2022,NaN
817,France,FR,Taux de croissance du PIB,NY.GDP.MKTP.KD.ZG,2022,2.45
841,France,FR,Population totale,SP.POP.TOTL,2022,"67,971,311.00"
865,France,FR,Taux de croissance de la population,SP.POP.GROW,2022,0.31
889,France,FR,Indice de fécondité,SP.DYN.TFRT.IN,2022,1.79
913,France,FR,Gini,SI.POV.GINI,2022,NaN
937,France,FR,Inflation (Indice des prix à la consommation),FP.CPI.TOTL.ZG,2022,5.22
961,France,FR,Taux d'intérêt réel,FR.INR.RINR,2022,NaN
985,France,FR,Taux de chômage,SL.UEM.TOTL.ZS,2022,7.31

In [36]:
df_countries[(df_countries["Année"] == "2022") & (df_countries["Code indicateur"] == "SP.POP.TOTL") ]

,Pays,Code pays,Indicateur,Code indicateur,Année,Valeur
169,Etats-Unis,US,Population totale,SP.POP.TOTL,2022,"333,271,411.00"
505,Chine,CN,Population totale,SP.POP.TOTL,2022,"1,412,175,000.00"
841,France,FR,Population totale,SP.POP.TOTL,2022,"67,971,311.00"
1177,Royaume-Uni,GB,Population totale,SP.POP.TOTL,2022,"67,791,000.00"
1513,Allemagne,DE,Population totale,SP.POP.TOTL,2022,"83,797,985.00"
1849,Cameroun,CM,Population totale,SP.POP.TOTL,2022,"27,914,536.00"

In [37]:
import requests
import pandas as pd

# Fonction pour récupérer les données d'un indicateur pour un pays spécifique sur une année donnée
def get_indicator_for_country_year(country_code, indicator_code, year):
    url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
    params = {
        "date": year,
        "format": "json",
        "per_page": 1000
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data and len(data) > 1 and data[1]:
            return data[1][0]['value']  # Récupérer la valeur pour cette année
    return None  # Si les données ne sont pas disponibles

# Chargement du DataFrame de pays avec les codes ISO
# Exemple : df_countries = pd.read_csv('countries.csv')
# Le DataFrame doit avoir une colonne 'Code ISO' ou similaire

In [39]:
# Exemple d'un DataFrame simple avec les codes ISO de certains pays
data = {'Pays': ['Etats-Unis', 'Chine', 'France', 'Allemagne', 'Cameroun'],
        'Code ISO': ['US', 'CN', 'FR', 'DE', 'CM']}
data_countries = pd.DataFrame(data)

data_countries

         Pays Code ISO
0  Etats-Unis       US
1       Chine       CN
2      France       FR
3   Allemagne       DE
4    Cameroun       CM

In [40]:
# Indicateur à ajouter (exemple: PIB par habitant)
indicator_code = 'NY.GDP.PCAP.CD'
year = '2022'

# Ajouter une nouvelle colonne avec les valeurs de l'indicateur
data_countries[f'PIB par habitant {year}'] = data_countries['Code ISO'].apply(
    lambda code: get_indicator_for_country_year(code, indicator_code, year)
)

# Afficher le DataFrame avec la nouvelle colonne
data_countries

         Pays Code ISO  PIB par habitant 2022
0  Etats-Unis       US           77246.673883
1       Chine       CN           12662.583169
2      France       FR           40886.253268
3   Allemagne       DE           48717.991140
4    Cameroun       CM            1563.488940

In [41]:
# Exemple d'un DataFrame simple avec les codes ISO de certains pays
data = {'Pays': ['Etats-Unis', 'Chine', 'France', 'Allemagne', 'Cameroun'],
        'Code ISO': ['US', 'CN', 'FR', 'DE', 'CM']}
df_countries_ind = pd.DataFrame(data)


# Liste des indicateurs à ajouter (code et nom)
indicators = {
    "PIB par habitant": 'NY.GDP.PCAP.CD',
    "PNB": 'NY.GNP.MKTP.CD',
    "Exportations": 'NE.EXP.GNFS.CD',
    "Importations": 'NE.IMP.GNFS.CD',
    "Taux de croissance du PIB": 'NY.GDP.MKTP.KD.ZG',
    "Population totale": 'SP.POP.TOTL',
    "Inflation": 'FP.CPI.TOTL.ZG',
    "Taux de chômage": 'SL.UEM.TOTL.ZS'
}

year = '2022'  # Année pour laquelle vous voulez récupérer les données

# Itérer sur la liste des indicateurs pour les ajouter au DataFrame
for indicator_name, indicator_code in indicators.items():
    df_countries_ind[indicator_name] = df_countries_ind['Code ISO'].apply(
        lambda code: get_indicator_for_country_year(code, indicator_code, year)
    )

# Afficher le DataFrame avec les nouvelles colonnes d'indicateurs
df_countries_ind

,Pays,Code ISO,PIB par habitant,PNB,Exportations,Importations,Taux de croissance du PIB,Population totale,Inflation,Taux de chômage
0,Etats-Unis,US,77246.673883,2.592600e+13,2.995046e+12,3.966165e+12,1.935496,333271411,8.002800,3.650
1,Chine,CN,12662.583169,1.777085e+13,3.717888e+12,3.140041e+12,2.989084,1412175000,1.973576,4.980
2,France,FR,40886.253268,2.828315e+12,9.639670e+11,1.071714e+12,2.454758,67971311,5.222367,7.308
3,Allemagne,DE,48717.991140,4.241259e+12,2.078954e+12,1.998631e+12,1.806209,83797985,6.872574,3.135
4,Cameroun,CM,1563.488940,4.253723e+10,8.419588e+09,9.599690e+09,3.582796,27914536,6.247677,3.687